# Generated by Django 3.1.7 on 2021-03-10 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_remove_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='datetime',
            field=models.DateField(default='2021-03-10'),
        ),
    ]
