# Generated by Django 3.1.7 on 2021-03-11 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20210310_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='datetime',
            field=models.DateField(default='2021-03-11'),
        ),
    ]
