# Generated by Django 3.1.7 on 2021-03-12 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20210311_2101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likes',
            old_name='User',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='post',
            name='datetime',
            field=models.DateField(default='2021-03-12'),
        ),
    ]
